// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package myfirstmodule.proxies.microflows;

import java.util.HashMap;
import java.util.Map;
import com.mendix.core.Core;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.systemwideinterfaces.core.IMendixObject;

public class Microflows
{
	/**
	 * @deprecated
	 * The default constructor of the Microflows class should not be used.
	 * Use the static microflow invocation methods instead.
	 */
	@java.lang.Deprecated(since = "9.12", forRemoval = true)
	public Microflows() {}

	// These are the microflows for the MyFirstModule module
	public static myfirstmodule.proxies.API_Stock aCT_GetStock(IContext context, java.lang.String _stock)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("Stock", _stock);
		IMendixObject result = (IMendixObject)Core.microflowCall("MyFirstModule.ACT_GetStock").withParams(params).execute(context);
		return result == null ? null : myfirstmodule.proxies.API_Stock.initialize(context, result);
	}
	public static void aCT_HomePage(IContext context)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		Core.microflowCall("MyFirstModule.ACT_HomePage").withParams(params).execute(context);
	}
	public static void aCT_LoginHelper_Save(IContext context, myfirstmodule.proxies.LoginHelper _loginHelper)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("LoginHelper", _loginHelper == null ? null : _loginHelper.getMendixObject());
		Core.microflowCall("MyFirstModule.ACT_LoginHelper_Save").withParams(params).execute(context);
	}
	public static void aCT_SignUp_SendEmail(IContext context)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		Core.microflowCall("MyFirstModule.ACT_SignUp_SendEmail").withParams(params).execute(context);
	}
	public static void dL_Account_Confirm(IContext context, java.lang.String _token)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("Token", _token);
		Core.microflowCall("MyFirstModule.DL_Account_Confirm").withParams(params).execute(context);
	}
	public static myfirstmodule.proxies.LoginHelper dS_LoginHelper(IContext context)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		IMendixObject result = (IMendixObject)Core.microflowCall("MyFirstModule.DS_LoginHelper").withParams(params).execute(context);
		return result == null ? null : myfirstmodule.proxies.LoginHelper.initialize(context, result);
	}
	public static void sub_CreateAndSendEmail(IContext context, emailtemplate.proxies.EmailTemplate _emailTemplate, myfirstmodule.proxies.EmailHelper _emailHelper, java.lang.String _email)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("EmailTemplate", _emailTemplate == null ? null : _emailTemplate.getMendixObject());
		params.put("EmailHelper", _emailHelper == null ? null : _emailHelper.getMendixObject());
		params.put("Email", _email);
		Core.microflowCall("MyFirstModule.Sub_CreateAndSendEmail").withParams(params).execute(context);
	}
	public static void sub_SignUp_CreateAndSendEmail(IContext context, emailtemplate.proxies.EmailTemplate _emailTemplate, java.lang.String _emailAddress, myfirstmodule.proxies.EmailContent _emailContent)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("EmailTemplate", _emailTemplate == null ? null : _emailTemplate.getMendixObject());
		params.put("EmailAddress", _emailAddress);
		params.put("EmailContent", _emailContent == null ? null : _emailContent.getMendixObject());
		Core.microflowCall("MyFirstModule.Sub_SignUp_CreateAndSendEmail").withParams(params).execute(context);
	}
	public static myfirstmodule.proxies.SumProfit sUM_Profit(IContext context)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		IMendixObject result = (IMendixObject)Core.microflowCall("MyFirstModule.SUM_Profit").withParams(params).execute(context);
		return result == null ? null : myfirstmodule.proxies.SumProfit.initialize(context, result);
	}
	public static myfirstmodule.proxies.SumProfit sUM_Profit_NASDAQ(IContext context)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		IMendixObject result = (IMendixObject)Core.microflowCall("MyFirstModule.SUM_Profit_NASDAQ").withParams(params).execute(context);
		return result == null ? null : myfirstmodule.proxies.SumProfit.initialize(context, result);
	}
	public static myfirstmodule.proxies.SumProfit sUM_Profit_NYSE(IContext context)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		IMendixObject result = (IMendixObject)Core.microflowCall("MyFirstModule.SUM_Profit_NYSE").withParams(params).execute(context);
		return result == null ? null : myfirstmodule.proxies.SumProfit.initialize(context, result);
	}
}
