// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package myfirstmodule.proxies;

public class API_Stock
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject aPI_StockMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "MyFirstModule.API_Stock";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		Symbol("Symbol"),
		AssetType("AssetType"),
		Name("Name"),
		Description("Description"),
		CIK("CIK"),
		Exchange("Exchange"),
		Currency("Currency"),
		Country("Country"),
		Sector("Sector"),
		Industry("Industry"),
		Address("Address"),
		FiscalYearEnd("FiscalYearEnd"),
		LatestQuarter("LatestQuarter"),
		MarketCapitalization("MarketCapitalization"),
		EBITDA("EBITDA"),
		PERatio("PERatio"),
		PEGRatio("PEGRatio"),
		BookValue("BookValue"),
		DividendPerShare("DividendPerShare"),
		DividendYield("DividendYield"),
		EPS("EPS"),
		RevenuePerShareTTM("RevenuePerShareTTM"),
		ProfitMargin("ProfitMargin"),
		OperatingMarginTTM("OperatingMarginTTM"),
		ReturnOnAssetsTTM("ReturnOnAssetsTTM"),
		ReturnOnEquityTTM("ReturnOnEquityTTM"),
		RevenueTTM("RevenueTTM"),
		GrossProfitTTM("GrossProfitTTM"),
		DilutedEPSTTM("DilutedEPSTTM"),
		QuarterlyEarningsGrowthYOY("QuarterlyEarningsGrowthYOY"),
		QuarterlyRevenueGrowthYOY("QuarterlyRevenueGrowthYOY"),
		AnalystTargetPrice("AnalystTargetPrice"),
		TrailingPE("TrailingPE"),
		ForwardPE("ForwardPE"),
		PriceToSalesRatioTTM("PriceToSalesRatioTTM"),
		PriceToBookRatio("PriceToBookRatio"),
		EVToRevenue("EVToRevenue"),
		EVToEBITDA("EVToEBITDA"),
		Beta("Beta"),
		_52WeekHigh("_52WeekHigh"),
		_52WeekLow("_52WeekLow"),
		_50DayMovingAverage("_50DayMovingAverage"),
		_200DayMovingAverage("_200DayMovingAverage"),
		SharesOutstanding("SharesOutstanding"),
		DividendDate("DividendDate"),
		ExDividendDate("ExDividendDate");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public API_Stock(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected API_Stock(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject aPI_StockMendixObject)
	{
		if (aPI_StockMendixObject == null) {
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		}
		if (!com.mendix.core.Core.isSubClassOf(entityName, aPI_StockMendixObject.getType())) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	

		this.aPI_StockMendixObject = aPI_StockMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'API_Stock.load(IContext, IMendixIdentifier)' instead.
	 */
	@java.lang.Deprecated
	public static myfirstmodule.proxies.API_Stock initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return myfirstmodule.proxies.API_Stock.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static myfirstmodule.proxies.API_Stock initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new myfirstmodule.proxies.API_Stock(context, mendixObject);
	}

	public static myfirstmodule.proxies.API_Stock load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return myfirstmodule.proxies.API_Stock.initialize(context, mendixObject);
	}

	/**
	 * Commit the changes made on this proxy object.
	 * @throws com.mendix.core.CoreException
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 * @throws com.mendix.core.CoreException
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * @return value of Symbol
	 */
	public final java.lang.String getSymbol()
	{
		return getSymbol(getContext());
	}

	/**
	 * @param context
	 * @return value of Symbol
	 */
	public final java.lang.String getSymbol(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Symbol.toString());
	}

	/**
	 * Set value of Symbol
	 * @param symbol
	 */
	public final void setSymbol(java.lang.String symbol)
	{
		setSymbol(getContext(), symbol);
	}

	/**
	 * Set value of Symbol
	 * @param context
	 * @param symbol
	 */
	public final void setSymbol(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String symbol)
	{
		getMendixObject().setValue(context, MemberNames.Symbol.toString(), symbol);
	}

	/**
	 * @return value of AssetType
	 */
	public final java.lang.String getAssetType()
	{
		return getAssetType(getContext());
	}

	/**
	 * @param context
	 * @return value of AssetType
	 */
	public final java.lang.String getAssetType(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.AssetType.toString());
	}

	/**
	 * Set value of AssetType
	 * @param assettype
	 */
	public final void setAssetType(java.lang.String assettype)
	{
		setAssetType(getContext(), assettype);
	}

	/**
	 * Set value of AssetType
	 * @param context
	 * @param assettype
	 */
	public final void setAssetType(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String assettype)
	{
		getMendixObject().setValue(context, MemberNames.AssetType.toString(), assettype);
	}

	/**
	 * @return value of Name
	 */
	public final java.lang.String getName()
	{
		return getName(getContext());
	}

	/**
	 * @param context
	 * @return value of Name
	 */
	public final java.lang.String getName(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Name.toString());
	}

	/**
	 * Set value of Name
	 * @param name
	 */
	public final void setName(java.lang.String name)
	{
		setName(getContext(), name);
	}

	/**
	 * Set value of Name
	 * @param context
	 * @param name
	 */
	public final void setName(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String name)
	{
		getMendixObject().setValue(context, MemberNames.Name.toString(), name);
	}

	/**
	 * @return value of Description
	 */
	public final java.lang.String getDescription()
	{
		return getDescription(getContext());
	}

	/**
	 * @param context
	 * @return value of Description
	 */
	public final java.lang.String getDescription(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Description.toString());
	}

	/**
	 * Set value of Description
	 * @param description
	 */
	public final void setDescription(java.lang.String description)
	{
		setDescription(getContext(), description);
	}

	/**
	 * Set value of Description
	 * @param context
	 * @param description
	 */
	public final void setDescription(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String description)
	{
		getMendixObject().setValue(context, MemberNames.Description.toString(), description);
	}

	/**
	 * @return value of CIK
	 */
	public final java.lang.String getCIK()
	{
		return getCIK(getContext());
	}

	/**
	 * @param context
	 * @return value of CIK
	 */
	public final java.lang.String getCIK(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.CIK.toString());
	}

	/**
	 * Set value of CIK
	 * @param cik
	 */
	public final void setCIK(java.lang.String cik)
	{
		setCIK(getContext(), cik);
	}

	/**
	 * Set value of CIK
	 * @param context
	 * @param cik
	 */
	public final void setCIK(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String cik)
	{
		getMendixObject().setValue(context, MemberNames.CIK.toString(), cik);
	}

	/**
	 * @return value of Exchange
	 */
	public final java.lang.String getExchange()
	{
		return getExchange(getContext());
	}

	/**
	 * @param context
	 * @return value of Exchange
	 */
	public final java.lang.String getExchange(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Exchange.toString());
	}

	/**
	 * Set value of Exchange
	 * @param exchange
	 */
	public final void setExchange(java.lang.String exchange)
	{
		setExchange(getContext(), exchange);
	}

	/**
	 * Set value of Exchange
	 * @param context
	 * @param exchange
	 */
	public final void setExchange(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String exchange)
	{
		getMendixObject().setValue(context, MemberNames.Exchange.toString(), exchange);
	}

	/**
	 * @return value of Currency
	 */
	public final java.lang.String getCurrency()
	{
		return getCurrency(getContext());
	}

	/**
	 * @param context
	 * @return value of Currency
	 */
	public final java.lang.String getCurrency(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Currency.toString());
	}

	/**
	 * Set value of Currency
	 * @param currency
	 */
	public final void setCurrency(java.lang.String currency)
	{
		setCurrency(getContext(), currency);
	}

	/**
	 * Set value of Currency
	 * @param context
	 * @param currency
	 */
	public final void setCurrency(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String currency)
	{
		getMendixObject().setValue(context, MemberNames.Currency.toString(), currency);
	}

	/**
	 * @return value of Country
	 */
	public final java.lang.String getCountry()
	{
		return getCountry(getContext());
	}

	/**
	 * @param context
	 * @return value of Country
	 */
	public final java.lang.String getCountry(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Country.toString());
	}

	/**
	 * Set value of Country
	 * @param country
	 */
	public final void setCountry(java.lang.String country)
	{
		setCountry(getContext(), country);
	}

	/**
	 * Set value of Country
	 * @param context
	 * @param country
	 */
	public final void setCountry(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String country)
	{
		getMendixObject().setValue(context, MemberNames.Country.toString(), country);
	}

	/**
	 * @return value of Sector
	 */
	public final java.lang.String getSector()
	{
		return getSector(getContext());
	}

	/**
	 * @param context
	 * @return value of Sector
	 */
	public final java.lang.String getSector(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Sector.toString());
	}

	/**
	 * Set value of Sector
	 * @param sector
	 */
	public final void setSector(java.lang.String sector)
	{
		setSector(getContext(), sector);
	}

	/**
	 * Set value of Sector
	 * @param context
	 * @param sector
	 */
	public final void setSector(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String sector)
	{
		getMendixObject().setValue(context, MemberNames.Sector.toString(), sector);
	}

	/**
	 * @return value of Industry
	 */
	public final java.lang.String getIndustry()
	{
		return getIndustry(getContext());
	}

	/**
	 * @param context
	 * @return value of Industry
	 */
	public final java.lang.String getIndustry(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Industry.toString());
	}

	/**
	 * Set value of Industry
	 * @param industry
	 */
	public final void setIndustry(java.lang.String industry)
	{
		setIndustry(getContext(), industry);
	}

	/**
	 * Set value of Industry
	 * @param context
	 * @param industry
	 */
	public final void setIndustry(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String industry)
	{
		getMendixObject().setValue(context, MemberNames.Industry.toString(), industry);
	}

	/**
	 * @return value of Address
	 */
	public final java.lang.String getAddress()
	{
		return getAddress(getContext());
	}

	/**
	 * @param context
	 * @return value of Address
	 */
	public final java.lang.String getAddress(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Address.toString());
	}

	/**
	 * Set value of Address
	 * @param address
	 */
	public final void setAddress(java.lang.String address)
	{
		setAddress(getContext(), address);
	}

	/**
	 * Set value of Address
	 * @param context
	 * @param address
	 */
	public final void setAddress(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String address)
	{
		getMendixObject().setValue(context, MemberNames.Address.toString(), address);
	}

	/**
	 * @return value of FiscalYearEnd
	 */
	public final java.lang.String getFiscalYearEnd()
	{
		return getFiscalYearEnd(getContext());
	}

	/**
	 * @param context
	 * @return value of FiscalYearEnd
	 */
	public final java.lang.String getFiscalYearEnd(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.FiscalYearEnd.toString());
	}

	/**
	 * Set value of FiscalYearEnd
	 * @param fiscalyearend
	 */
	public final void setFiscalYearEnd(java.lang.String fiscalyearend)
	{
		setFiscalYearEnd(getContext(), fiscalyearend);
	}

	/**
	 * Set value of FiscalYearEnd
	 * @param context
	 * @param fiscalyearend
	 */
	public final void setFiscalYearEnd(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String fiscalyearend)
	{
		getMendixObject().setValue(context, MemberNames.FiscalYearEnd.toString(), fiscalyearend);
	}

	/**
	 * @return value of LatestQuarter
	 */
	public final java.lang.String getLatestQuarter()
	{
		return getLatestQuarter(getContext());
	}

	/**
	 * @param context
	 * @return value of LatestQuarter
	 */
	public final java.lang.String getLatestQuarter(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.LatestQuarter.toString());
	}

	/**
	 * Set value of LatestQuarter
	 * @param latestquarter
	 */
	public final void setLatestQuarter(java.lang.String latestquarter)
	{
		setLatestQuarter(getContext(), latestquarter);
	}

	/**
	 * Set value of LatestQuarter
	 * @param context
	 * @param latestquarter
	 */
	public final void setLatestQuarter(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String latestquarter)
	{
		getMendixObject().setValue(context, MemberNames.LatestQuarter.toString(), latestquarter);
	}

	/**
	 * @return value of MarketCapitalization
	 */
	public final java.lang.String getMarketCapitalization()
	{
		return getMarketCapitalization(getContext());
	}

	/**
	 * @param context
	 * @return value of MarketCapitalization
	 */
	public final java.lang.String getMarketCapitalization(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.MarketCapitalization.toString());
	}

	/**
	 * Set value of MarketCapitalization
	 * @param marketcapitalization
	 */
	public final void setMarketCapitalization(java.lang.String marketcapitalization)
	{
		setMarketCapitalization(getContext(), marketcapitalization);
	}

	/**
	 * Set value of MarketCapitalization
	 * @param context
	 * @param marketcapitalization
	 */
	public final void setMarketCapitalization(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String marketcapitalization)
	{
		getMendixObject().setValue(context, MemberNames.MarketCapitalization.toString(), marketcapitalization);
	}

	/**
	 * @return value of EBITDA
	 */
	public final java.lang.String getEBITDA()
	{
		return getEBITDA(getContext());
	}

	/**
	 * @param context
	 * @return value of EBITDA
	 */
	public final java.lang.String getEBITDA(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.EBITDA.toString());
	}

	/**
	 * Set value of EBITDA
	 * @param ebitda
	 */
	public final void setEBITDA(java.lang.String ebitda)
	{
		setEBITDA(getContext(), ebitda);
	}

	/**
	 * Set value of EBITDA
	 * @param context
	 * @param ebitda
	 */
	public final void setEBITDA(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String ebitda)
	{
		getMendixObject().setValue(context, MemberNames.EBITDA.toString(), ebitda);
	}

	/**
	 * @return value of PERatio
	 */
	public final java.lang.String getPERatio()
	{
		return getPERatio(getContext());
	}

	/**
	 * @param context
	 * @return value of PERatio
	 */
	public final java.lang.String getPERatio(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.PERatio.toString());
	}

	/**
	 * Set value of PERatio
	 * @param peratio
	 */
	public final void setPERatio(java.lang.String peratio)
	{
		setPERatio(getContext(), peratio);
	}

	/**
	 * Set value of PERatio
	 * @param context
	 * @param peratio
	 */
	public final void setPERatio(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String peratio)
	{
		getMendixObject().setValue(context, MemberNames.PERatio.toString(), peratio);
	}

	/**
	 * @return value of PEGRatio
	 */
	public final java.lang.String getPEGRatio()
	{
		return getPEGRatio(getContext());
	}

	/**
	 * @param context
	 * @return value of PEGRatio
	 */
	public final java.lang.String getPEGRatio(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.PEGRatio.toString());
	}

	/**
	 * Set value of PEGRatio
	 * @param pegratio
	 */
	public final void setPEGRatio(java.lang.String pegratio)
	{
		setPEGRatio(getContext(), pegratio);
	}

	/**
	 * Set value of PEGRatio
	 * @param context
	 * @param pegratio
	 */
	public final void setPEGRatio(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String pegratio)
	{
		getMendixObject().setValue(context, MemberNames.PEGRatio.toString(), pegratio);
	}

	/**
	 * @return value of BookValue
	 */
	public final java.lang.String getBookValue()
	{
		return getBookValue(getContext());
	}

	/**
	 * @param context
	 * @return value of BookValue
	 */
	public final java.lang.String getBookValue(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.BookValue.toString());
	}

	/**
	 * Set value of BookValue
	 * @param bookvalue
	 */
	public final void setBookValue(java.lang.String bookvalue)
	{
		setBookValue(getContext(), bookvalue);
	}

	/**
	 * Set value of BookValue
	 * @param context
	 * @param bookvalue
	 */
	public final void setBookValue(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String bookvalue)
	{
		getMendixObject().setValue(context, MemberNames.BookValue.toString(), bookvalue);
	}

	/**
	 * @return value of DividendPerShare
	 */
	public final java.lang.String getDividendPerShare()
	{
		return getDividendPerShare(getContext());
	}

	/**
	 * @param context
	 * @return value of DividendPerShare
	 */
	public final java.lang.String getDividendPerShare(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.DividendPerShare.toString());
	}

	/**
	 * Set value of DividendPerShare
	 * @param dividendpershare
	 */
	public final void setDividendPerShare(java.lang.String dividendpershare)
	{
		setDividendPerShare(getContext(), dividendpershare);
	}

	/**
	 * Set value of DividendPerShare
	 * @param context
	 * @param dividendpershare
	 */
	public final void setDividendPerShare(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String dividendpershare)
	{
		getMendixObject().setValue(context, MemberNames.DividendPerShare.toString(), dividendpershare);
	}

	/**
	 * @return value of DividendYield
	 */
	public final java.lang.String getDividendYield()
	{
		return getDividendYield(getContext());
	}

	/**
	 * @param context
	 * @return value of DividendYield
	 */
	public final java.lang.String getDividendYield(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.DividendYield.toString());
	}

	/**
	 * Set value of DividendYield
	 * @param dividendyield
	 */
	public final void setDividendYield(java.lang.String dividendyield)
	{
		setDividendYield(getContext(), dividendyield);
	}

	/**
	 * Set value of DividendYield
	 * @param context
	 * @param dividendyield
	 */
	public final void setDividendYield(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String dividendyield)
	{
		getMendixObject().setValue(context, MemberNames.DividendYield.toString(), dividendyield);
	}

	/**
	 * @return value of EPS
	 */
	public final java.lang.String getEPS()
	{
		return getEPS(getContext());
	}

	/**
	 * @param context
	 * @return value of EPS
	 */
	public final java.lang.String getEPS(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.EPS.toString());
	}

	/**
	 * Set value of EPS
	 * @param eps
	 */
	public final void setEPS(java.lang.String eps)
	{
		setEPS(getContext(), eps);
	}

	/**
	 * Set value of EPS
	 * @param context
	 * @param eps
	 */
	public final void setEPS(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String eps)
	{
		getMendixObject().setValue(context, MemberNames.EPS.toString(), eps);
	}

	/**
	 * @return value of RevenuePerShareTTM
	 */
	public final java.lang.String getRevenuePerShareTTM()
	{
		return getRevenuePerShareTTM(getContext());
	}

	/**
	 * @param context
	 * @return value of RevenuePerShareTTM
	 */
	public final java.lang.String getRevenuePerShareTTM(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.RevenuePerShareTTM.toString());
	}

	/**
	 * Set value of RevenuePerShareTTM
	 * @param revenuepersharettm
	 */
	public final void setRevenuePerShareTTM(java.lang.String revenuepersharettm)
	{
		setRevenuePerShareTTM(getContext(), revenuepersharettm);
	}

	/**
	 * Set value of RevenuePerShareTTM
	 * @param context
	 * @param revenuepersharettm
	 */
	public final void setRevenuePerShareTTM(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String revenuepersharettm)
	{
		getMendixObject().setValue(context, MemberNames.RevenuePerShareTTM.toString(), revenuepersharettm);
	}

	/**
	 * @return value of ProfitMargin
	 */
	public final java.lang.String getProfitMargin()
	{
		return getProfitMargin(getContext());
	}

	/**
	 * @param context
	 * @return value of ProfitMargin
	 */
	public final java.lang.String getProfitMargin(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.ProfitMargin.toString());
	}

	/**
	 * Set value of ProfitMargin
	 * @param profitmargin
	 */
	public final void setProfitMargin(java.lang.String profitmargin)
	{
		setProfitMargin(getContext(), profitmargin);
	}

	/**
	 * Set value of ProfitMargin
	 * @param context
	 * @param profitmargin
	 */
	public final void setProfitMargin(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String profitmargin)
	{
		getMendixObject().setValue(context, MemberNames.ProfitMargin.toString(), profitmargin);
	}

	/**
	 * @return value of OperatingMarginTTM
	 */
	public final java.lang.String getOperatingMarginTTM()
	{
		return getOperatingMarginTTM(getContext());
	}

	/**
	 * @param context
	 * @return value of OperatingMarginTTM
	 */
	public final java.lang.String getOperatingMarginTTM(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.OperatingMarginTTM.toString());
	}

	/**
	 * Set value of OperatingMarginTTM
	 * @param operatingmarginttm
	 */
	public final void setOperatingMarginTTM(java.lang.String operatingmarginttm)
	{
		setOperatingMarginTTM(getContext(), operatingmarginttm);
	}

	/**
	 * Set value of OperatingMarginTTM
	 * @param context
	 * @param operatingmarginttm
	 */
	public final void setOperatingMarginTTM(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String operatingmarginttm)
	{
		getMendixObject().setValue(context, MemberNames.OperatingMarginTTM.toString(), operatingmarginttm);
	}

	/**
	 * @return value of ReturnOnAssetsTTM
	 */
	public final java.lang.String getReturnOnAssetsTTM()
	{
		return getReturnOnAssetsTTM(getContext());
	}

	/**
	 * @param context
	 * @return value of ReturnOnAssetsTTM
	 */
	public final java.lang.String getReturnOnAssetsTTM(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.ReturnOnAssetsTTM.toString());
	}

	/**
	 * Set value of ReturnOnAssetsTTM
	 * @param returnonassetsttm
	 */
	public final void setReturnOnAssetsTTM(java.lang.String returnonassetsttm)
	{
		setReturnOnAssetsTTM(getContext(), returnonassetsttm);
	}

	/**
	 * Set value of ReturnOnAssetsTTM
	 * @param context
	 * @param returnonassetsttm
	 */
	public final void setReturnOnAssetsTTM(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String returnonassetsttm)
	{
		getMendixObject().setValue(context, MemberNames.ReturnOnAssetsTTM.toString(), returnonassetsttm);
	}

	/**
	 * @return value of ReturnOnEquityTTM
	 */
	public final java.lang.String getReturnOnEquityTTM()
	{
		return getReturnOnEquityTTM(getContext());
	}

	/**
	 * @param context
	 * @return value of ReturnOnEquityTTM
	 */
	public final java.lang.String getReturnOnEquityTTM(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.ReturnOnEquityTTM.toString());
	}

	/**
	 * Set value of ReturnOnEquityTTM
	 * @param returnonequityttm
	 */
	public final void setReturnOnEquityTTM(java.lang.String returnonequityttm)
	{
		setReturnOnEquityTTM(getContext(), returnonequityttm);
	}

	/**
	 * Set value of ReturnOnEquityTTM
	 * @param context
	 * @param returnonequityttm
	 */
	public final void setReturnOnEquityTTM(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String returnonequityttm)
	{
		getMendixObject().setValue(context, MemberNames.ReturnOnEquityTTM.toString(), returnonequityttm);
	}

	/**
	 * @return value of RevenueTTM
	 */
	public final java.lang.String getRevenueTTM()
	{
		return getRevenueTTM(getContext());
	}

	/**
	 * @param context
	 * @return value of RevenueTTM
	 */
	public final java.lang.String getRevenueTTM(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.RevenueTTM.toString());
	}

	/**
	 * Set value of RevenueTTM
	 * @param revenuettm
	 */
	public final void setRevenueTTM(java.lang.String revenuettm)
	{
		setRevenueTTM(getContext(), revenuettm);
	}

	/**
	 * Set value of RevenueTTM
	 * @param context
	 * @param revenuettm
	 */
	public final void setRevenueTTM(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String revenuettm)
	{
		getMendixObject().setValue(context, MemberNames.RevenueTTM.toString(), revenuettm);
	}

	/**
	 * @return value of GrossProfitTTM
	 */
	public final java.lang.String getGrossProfitTTM()
	{
		return getGrossProfitTTM(getContext());
	}

	/**
	 * @param context
	 * @return value of GrossProfitTTM
	 */
	public final java.lang.String getGrossProfitTTM(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.GrossProfitTTM.toString());
	}

	/**
	 * Set value of GrossProfitTTM
	 * @param grossprofitttm
	 */
	public final void setGrossProfitTTM(java.lang.String grossprofitttm)
	{
		setGrossProfitTTM(getContext(), grossprofitttm);
	}

	/**
	 * Set value of GrossProfitTTM
	 * @param context
	 * @param grossprofitttm
	 */
	public final void setGrossProfitTTM(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String grossprofitttm)
	{
		getMendixObject().setValue(context, MemberNames.GrossProfitTTM.toString(), grossprofitttm);
	}

	/**
	 * @return value of DilutedEPSTTM
	 */
	public final java.lang.String getDilutedEPSTTM()
	{
		return getDilutedEPSTTM(getContext());
	}

	/**
	 * @param context
	 * @return value of DilutedEPSTTM
	 */
	public final java.lang.String getDilutedEPSTTM(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.DilutedEPSTTM.toString());
	}

	/**
	 * Set value of DilutedEPSTTM
	 * @param dilutedepsttm
	 */
	public final void setDilutedEPSTTM(java.lang.String dilutedepsttm)
	{
		setDilutedEPSTTM(getContext(), dilutedepsttm);
	}

	/**
	 * Set value of DilutedEPSTTM
	 * @param context
	 * @param dilutedepsttm
	 */
	public final void setDilutedEPSTTM(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String dilutedepsttm)
	{
		getMendixObject().setValue(context, MemberNames.DilutedEPSTTM.toString(), dilutedepsttm);
	}

	/**
	 * @return value of QuarterlyEarningsGrowthYOY
	 */
	public final java.lang.String getQuarterlyEarningsGrowthYOY()
	{
		return getQuarterlyEarningsGrowthYOY(getContext());
	}

	/**
	 * @param context
	 * @return value of QuarterlyEarningsGrowthYOY
	 */
	public final java.lang.String getQuarterlyEarningsGrowthYOY(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.QuarterlyEarningsGrowthYOY.toString());
	}

	/**
	 * Set value of QuarterlyEarningsGrowthYOY
	 * @param quarterlyearningsgrowthyoy
	 */
	public final void setQuarterlyEarningsGrowthYOY(java.lang.String quarterlyearningsgrowthyoy)
	{
		setQuarterlyEarningsGrowthYOY(getContext(), quarterlyearningsgrowthyoy);
	}

	/**
	 * Set value of QuarterlyEarningsGrowthYOY
	 * @param context
	 * @param quarterlyearningsgrowthyoy
	 */
	public final void setQuarterlyEarningsGrowthYOY(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String quarterlyearningsgrowthyoy)
	{
		getMendixObject().setValue(context, MemberNames.QuarterlyEarningsGrowthYOY.toString(), quarterlyearningsgrowthyoy);
	}

	/**
	 * @return value of QuarterlyRevenueGrowthYOY
	 */
	public final java.lang.String getQuarterlyRevenueGrowthYOY()
	{
		return getQuarterlyRevenueGrowthYOY(getContext());
	}

	/**
	 * @param context
	 * @return value of QuarterlyRevenueGrowthYOY
	 */
	public final java.lang.String getQuarterlyRevenueGrowthYOY(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.QuarterlyRevenueGrowthYOY.toString());
	}

	/**
	 * Set value of QuarterlyRevenueGrowthYOY
	 * @param quarterlyrevenuegrowthyoy
	 */
	public final void setQuarterlyRevenueGrowthYOY(java.lang.String quarterlyrevenuegrowthyoy)
	{
		setQuarterlyRevenueGrowthYOY(getContext(), quarterlyrevenuegrowthyoy);
	}

	/**
	 * Set value of QuarterlyRevenueGrowthYOY
	 * @param context
	 * @param quarterlyrevenuegrowthyoy
	 */
	public final void setQuarterlyRevenueGrowthYOY(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String quarterlyrevenuegrowthyoy)
	{
		getMendixObject().setValue(context, MemberNames.QuarterlyRevenueGrowthYOY.toString(), quarterlyrevenuegrowthyoy);
	}

	/**
	 * @return value of AnalystTargetPrice
	 */
	public final java.lang.String getAnalystTargetPrice()
	{
		return getAnalystTargetPrice(getContext());
	}

	/**
	 * @param context
	 * @return value of AnalystTargetPrice
	 */
	public final java.lang.String getAnalystTargetPrice(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.AnalystTargetPrice.toString());
	}

	/**
	 * Set value of AnalystTargetPrice
	 * @param analysttargetprice
	 */
	public final void setAnalystTargetPrice(java.lang.String analysttargetprice)
	{
		setAnalystTargetPrice(getContext(), analysttargetprice);
	}

	/**
	 * Set value of AnalystTargetPrice
	 * @param context
	 * @param analysttargetprice
	 */
	public final void setAnalystTargetPrice(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String analysttargetprice)
	{
		getMendixObject().setValue(context, MemberNames.AnalystTargetPrice.toString(), analysttargetprice);
	}

	/**
	 * @return value of TrailingPE
	 */
	public final java.lang.String getTrailingPE()
	{
		return getTrailingPE(getContext());
	}

	/**
	 * @param context
	 * @return value of TrailingPE
	 */
	public final java.lang.String getTrailingPE(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.TrailingPE.toString());
	}

	/**
	 * Set value of TrailingPE
	 * @param trailingpe
	 */
	public final void setTrailingPE(java.lang.String trailingpe)
	{
		setTrailingPE(getContext(), trailingpe);
	}

	/**
	 * Set value of TrailingPE
	 * @param context
	 * @param trailingpe
	 */
	public final void setTrailingPE(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String trailingpe)
	{
		getMendixObject().setValue(context, MemberNames.TrailingPE.toString(), trailingpe);
	}

	/**
	 * @return value of ForwardPE
	 */
	public final java.lang.String getForwardPE()
	{
		return getForwardPE(getContext());
	}

	/**
	 * @param context
	 * @return value of ForwardPE
	 */
	public final java.lang.String getForwardPE(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.ForwardPE.toString());
	}

	/**
	 * Set value of ForwardPE
	 * @param forwardpe
	 */
	public final void setForwardPE(java.lang.String forwardpe)
	{
		setForwardPE(getContext(), forwardpe);
	}

	/**
	 * Set value of ForwardPE
	 * @param context
	 * @param forwardpe
	 */
	public final void setForwardPE(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String forwardpe)
	{
		getMendixObject().setValue(context, MemberNames.ForwardPE.toString(), forwardpe);
	}

	/**
	 * @return value of PriceToSalesRatioTTM
	 */
	public final java.lang.String getPriceToSalesRatioTTM()
	{
		return getPriceToSalesRatioTTM(getContext());
	}

	/**
	 * @param context
	 * @return value of PriceToSalesRatioTTM
	 */
	public final java.lang.String getPriceToSalesRatioTTM(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.PriceToSalesRatioTTM.toString());
	}

	/**
	 * Set value of PriceToSalesRatioTTM
	 * @param pricetosalesratiottm
	 */
	public final void setPriceToSalesRatioTTM(java.lang.String pricetosalesratiottm)
	{
		setPriceToSalesRatioTTM(getContext(), pricetosalesratiottm);
	}

	/**
	 * Set value of PriceToSalesRatioTTM
	 * @param context
	 * @param pricetosalesratiottm
	 */
	public final void setPriceToSalesRatioTTM(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String pricetosalesratiottm)
	{
		getMendixObject().setValue(context, MemberNames.PriceToSalesRatioTTM.toString(), pricetosalesratiottm);
	}

	/**
	 * @return value of PriceToBookRatio
	 */
	public final java.lang.String getPriceToBookRatio()
	{
		return getPriceToBookRatio(getContext());
	}

	/**
	 * @param context
	 * @return value of PriceToBookRatio
	 */
	public final java.lang.String getPriceToBookRatio(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.PriceToBookRatio.toString());
	}

	/**
	 * Set value of PriceToBookRatio
	 * @param pricetobookratio
	 */
	public final void setPriceToBookRatio(java.lang.String pricetobookratio)
	{
		setPriceToBookRatio(getContext(), pricetobookratio);
	}

	/**
	 * Set value of PriceToBookRatio
	 * @param context
	 * @param pricetobookratio
	 */
	public final void setPriceToBookRatio(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String pricetobookratio)
	{
		getMendixObject().setValue(context, MemberNames.PriceToBookRatio.toString(), pricetobookratio);
	}

	/**
	 * @return value of EVToRevenue
	 */
	public final java.lang.String getEVToRevenue()
	{
		return getEVToRevenue(getContext());
	}

	/**
	 * @param context
	 * @return value of EVToRevenue
	 */
	public final java.lang.String getEVToRevenue(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.EVToRevenue.toString());
	}

	/**
	 * Set value of EVToRevenue
	 * @param evtorevenue
	 */
	public final void setEVToRevenue(java.lang.String evtorevenue)
	{
		setEVToRevenue(getContext(), evtorevenue);
	}

	/**
	 * Set value of EVToRevenue
	 * @param context
	 * @param evtorevenue
	 */
	public final void setEVToRevenue(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String evtorevenue)
	{
		getMendixObject().setValue(context, MemberNames.EVToRevenue.toString(), evtorevenue);
	}

	/**
	 * @return value of EVToEBITDA
	 */
	public final java.lang.String getEVToEBITDA()
	{
		return getEVToEBITDA(getContext());
	}

	/**
	 * @param context
	 * @return value of EVToEBITDA
	 */
	public final java.lang.String getEVToEBITDA(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.EVToEBITDA.toString());
	}

	/**
	 * Set value of EVToEBITDA
	 * @param evtoebitda
	 */
	public final void setEVToEBITDA(java.lang.String evtoebitda)
	{
		setEVToEBITDA(getContext(), evtoebitda);
	}

	/**
	 * Set value of EVToEBITDA
	 * @param context
	 * @param evtoebitda
	 */
	public final void setEVToEBITDA(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String evtoebitda)
	{
		getMendixObject().setValue(context, MemberNames.EVToEBITDA.toString(), evtoebitda);
	}

	/**
	 * @return value of Beta
	 */
	public final java.lang.String getBeta()
	{
		return getBeta(getContext());
	}

	/**
	 * @param context
	 * @return value of Beta
	 */
	public final java.lang.String getBeta(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Beta.toString());
	}

	/**
	 * Set value of Beta
	 * @param beta
	 */
	public final void setBeta(java.lang.String beta)
	{
		setBeta(getContext(), beta);
	}

	/**
	 * Set value of Beta
	 * @param context
	 * @param beta
	 */
	public final void setBeta(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String beta)
	{
		getMendixObject().setValue(context, MemberNames.Beta.toString(), beta);
	}

	/**
	 * @return value of _52WeekHigh
	 */
	public final java.lang.String get_52WeekHigh()
	{
		return get_52WeekHigh(getContext());
	}

	/**
	 * @param context
	 * @return value of _52WeekHigh
	 */
	public final java.lang.String get_52WeekHigh(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames._52WeekHigh.toString());
	}

	/**
	 * Set value of _52WeekHigh
	 * @param _52weekhigh
	 */
	public final void set_52WeekHigh(java.lang.String _52weekhigh)
	{
		set_52WeekHigh(getContext(), _52weekhigh);
	}

	/**
	 * Set value of _52WeekHigh
	 * @param context
	 * @param _52weekhigh
	 */
	public final void set_52WeekHigh(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String _52weekhigh)
	{
		getMendixObject().setValue(context, MemberNames._52WeekHigh.toString(), _52weekhigh);
	}

	/**
	 * @return value of _52WeekLow
	 */
	public final java.lang.String get_52WeekLow()
	{
		return get_52WeekLow(getContext());
	}

	/**
	 * @param context
	 * @return value of _52WeekLow
	 */
	public final java.lang.String get_52WeekLow(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames._52WeekLow.toString());
	}

	/**
	 * Set value of _52WeekLow
	 * @param _52weeklow
	 */
	public final void set_52WeekLow(java.lang.String _52weeklow)
	{
		set_52WeekLow(getContext(), _52weeklow);
	}

	/**
	 * Set value of _52WeekLow
	 * @param context
	 * @param _52weeklow
	 */
	public final void set_52WeekLow(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String _52weeklow)
	{
		getMendixObject().setValue(context, MemberNames._52WeekLow.toString(), _52weeklow);
	}

	/**
	 * @return value of _50DayMovingAverage
	 */
	public final java.lang.String get_50DayMovingAverage()
	{
		return get_50DayMovingAverage(getContext());
	}

	/**
	 * @param context
	 * @return value of _50DayMovingAverage
	 */
	public final java.lang.String get_50DayMovingAverage(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames._50DayMovingAverage.toString());
	}

	/**
	 * Set value of _50DayMovingAverage
	 * @param _50daymovingaverage
	 */
	public final void set_50DayMovingAverage(java.lang.String _50daymovingaverage)
	{
		set_50DayMovingAverage(getContext(), _50daymovingaverage);
	}

	/**
	 * Set value of _50DayMovingAverage
	 * @param context
	 * @param _50daymovingaverage
	 */
	public final void set_50DayMovingAverage(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String _50daymovingaverage)
	{
		getMendixObject().setValue(context, MemberNames._50DayMovingAverage.toString(), _50daymovingaverage);
	}

	/**
	 * @return value of _200DayMovingAverage
	 */
	public final java.lang.String get_200DayMovingAverage()
	{
		return get_200DayMovingAverage(getContext());
	}

	/**
	 * @param context
	 * @return value of _200DayMovingAverage
	 */
	public final java.lang.String get_200DayMovingAverage(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames._200DayMovingAverage.toString());
	}

	/**
	 * Set value of _200DayMovingAverage
	 * @param _200daymovingaverage
	 */
	public final void set_200DayMovingAverage(java.lang.String _200daymovingaverage)
	{
		set_200DayMovingAverage(getContext(), _200daymovingaverage);
	}

	/**
	 * Set value of _200DayMovingAverage
	 * @param context
	 * @param _200daymovingaverage
	 */
	public final void set_200DayMovingAverage(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String _200daymovingaverage)
	{
		getMendixObject().setValue(context, MemberNames._200DayMovingAverage.toString(), _200daymovingaverage);
	}

	/**
	 * @return value of SharesOutstanding
	 */
	public final java.lang.String getSharesOutstanding()
	{
		return getSharesOutstanding(getContext());
	}

	/**
	 * @param context
	 * @return value of SharesOutstanding
	 */
	public final java.lang.String getSharesOutstanding(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.SharesOutstanding.toString());
	}

	/**
	 * Set value of SharesOutstanding
	 * @param sharesoutstanding
	 */
	public final void setSharesOutstanding(java.lang.String sharesoutstanding)
	{
		setSharesOutstanding(getContext(), sharesoutstanding);
	}

	/**
	 * Set value of SharesOutstanding
	 * @param context
	 * @param sharesoutstanding
	 */
	public final void setSharesOutstanding(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String sharesoutstanding)
	{
		getMendixObject().setValue(context, MemberNames.SharesOutstanding.toString(), sharesoutstanding);
	}

	/**
	 * @return value of DividendDate
	 */
	public final java.lang.String getDividendDate()
	{
		return getDividendDate(getContext());
	}

	/**
	 * @param context
	 * @return value of DividendDate
	 */
	public final java.lang.String getDividendDate(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.DividendDate.toString());
	}

	/**
	 * Set value of DividendDate
	 * @param dividenddate
	 */
	public final void setDividendDate(java.lang.String dividenddate)
	{
		setDividendDate(getContext(), dividenddate);
	}

	/**
	 * Set value of DividendDate
	 * @param context
	 * @param dividenddate
	 */
	public final void setDividendDate(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String dividenddate)
	{
		getMendixObject().setValue(context, MemberNames.DividendDate.toString(), dividenddate);
	}

	/**
	 * @return value of ExDividendDate
	 */
	public final java.lang.String getExDividendDate()
	{
		return getExDividendDate(getContext());
	}

	/**
	 * @param context
	 * @return value of ExDividendDate
	 */
	public final java.lang.String getExDividendDate(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.ExDividendDate.toString());
	}

	/**
	 * Set value of ExDividendDate
	 * @param exdividenddate
	 */
	public final void setExDividendDate(java.lang.String exdividenddate)
	{
		setExDividendDate(getContext(), exdividenddate);
	}

	/**
	 * Set value of ExDividendDate
	 * @param context
	 * @param exdividenddate
	 */
	public final void setExDividendDate(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String exdividenddate)
	{
		getMendixObject().setValue(context, MemberNames.ExDividendDate.toString(), exdividenddate);
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return aPI_StockMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final myfirstmodule.proxies.API_Stock that = (myfirstmodule.proxies.API_Stock) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return entityName;
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@java.lang.Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
